# Generated by Django 2.1.3 on 2018-11-20 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('texto', models.CharField(max_length=150)),
                ('cuerpo', models.TextField()),
                ('url', models.FileField(upload_to='')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('categorias', models.CharField(choices=[('PYT', 'Python'), ('DJA', 'Django'), ('RES', 'Rest')], max_length=3)),
            ],
        ),
    ]
