# Generated by Django 2.1.3 on 2018-12-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blog_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='publicado',
            field=models.CharField(choices=[('PUB', 'Publicado'), ('EDT', 'Editado'), ('ELM', 'Eliminado')], default=1, max_length=3),
            preserve_default=False,
        ),
    ]
