# Generated by Django 2.1.3 on 2018-12-26 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0004_blog_publicado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='usuario',
        ),
        migrations.AddField(
            model_name='blog',
            name='owner',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blog', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
