# Generated by Django 2.1.3 on 2018-12-26 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20181226_2039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='owner',
            new_name='usuario',
        ),
    ]
